app/models/Room.py
from ..config.database import db

class Room(db.Model):
    __tablename__ = "room"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    room_name = db.Column(db.String(80), nullable=False, unique=True)
    image1 = db.Column(db.String(255))
    image2 = db.Column(db.String(255))
    image3 = db.Column(db.String(255))
    view = db.Column(db.String(80))
    width = db.Column(db.String(80))
    max_occupancy = db.Column(db.Integer)
    price = db.Column(db.Float, nullable=False)
    description = db.Column(db.Text)
    status = db.Column(db.String(20), default="available")

    
    def __init__(self, room_name, image1, image2, image3, view, width, max_occupancy, price, description, status="available"):
        self.room_name = room_name
        self.image1 = image1
        self.image2 = image2
        self.image3 = image3
        self.view = view
        self.width = width
        self.max_occupancy = max_occupancy
        self.price = price
        self.description = description
        self.status = status

    
  
    def get_all(cls):
        rooms = cls.query.all()
        return rooms
  

    def find_by_id(cls, id):
        room = cls.query.filter_by(id=id)
        return room

    def data(self):
        return {
        "room_name": self.room_name,    
        "image1": self.image1,
        "image2": self.image2,
        "image3": self.image3,
        "view": self.view,
        "width": self.width,
        "max_occupancy": self.max_occupancy,
        "price": self.price,
        "description": self.description,
        "status": self.status,
        }

app/views/rooms.py
import datetime
from datetime import datetime
from flask import Blueprint, jsonify, request, render_template, redirect, session, url_for, flash
from app.models.Bookings import Booking
from app.views.decorators import user_logged_in
from ..models import Room, Token
from ..config.database import db

room = Blueprint("room", __name__) 

# To add a new room
@room.route("/room", methods=["POST"])
def room_page():
    if request.method == "POST":
        # Get data from the form.
        name = request.form.get("room_name")
        image1 = request.form.get("image1")
        image2 = request.form.get("image2")
        image3 = request.form.get("image3")
        description = request.form.get("description")
        max_occupancy = request.form.get("max_occupancy")
        view = request.form.get("view")
        status = request.form.get("status")
        price = request.form.get("price")
        width = request.form.get("width")

        print(f"request : {request.form}")

        # Check if required fields are not empty.
        if not image1 or not description or not max_occupancy or not price:
            flash("Please provide values for required fields", "error")
            return redirect(url_for("admin.room_page"))

        # Validate max_occupancy is a positive integer.
        if not max_occupancy.isnumeric() or int(max_occupancy) <= 0:
            flash("Max occupancy must be a positive integer", "error")
            return redirect(url_for("admin.room_page"))

        # Validate price is a positive float.
        try:
            price = float(price)
            if price <= 0:
                raise ValueError
        except ValueError:
            flash("Price must be a positive number", "error")
            return redirect(url_for("admin.room_page"))

        # Create a Room instance and add it to the database.
        new_room = Room(room_name=name, image1=image1, image2=image2, image3=image3, view=view, width=width,
                        max_occupancy=int(max_occupancy), price=price, description=description, status=status)
        db.session.add(new_room)
        db.session.commit()

        # Redirect to the page where you want to show the updated list of rooms.
        flash("Room added successfully", "success")
        return redirect(url_for("admin.room_page"))

# To update existing room
@room.route("/room/update/<int:room_id>", methods=["POST"])
def update_room(room_id):
 if request.method == "POST":
    # Get data from the form.
    room_name = request.form.get("room_name")
    description = request.form.get("description")
    max_occupancy = request.form.get("max_occupancy")
    view = request.form.get("view")
    status = request.form.get("status")
    price = request.form.get("price")
    width = request.form.get("width")

    # Check if required fields are not empty.
    if not room_name or not description or not max_occupancy or not price:
        flash("Please provide values for required fields", "error")
        return redirect(url_for("admin.room_page"))

    # Validate max_occupancy is a positive integer.
    if not max_occupancy.isnumeric() or int(max_occupancy) <= 0:
        flash("Max occupancy must be a positive integer", "error")
        return redirect(url_for("admin.room_page"))

    # Validate price is a positive float.
    try:
        price = float(price)
        if price <= 0:
            raise ValueError
    except ValueError:
        flash("Price must be a positive number", "error")
        return redirect(url_for("admin.room_page"))

    # Retrieve the original image values from the database.
    room = Room.query.get(room_id)
    if room:
        original_image1 = room.image1
        original_image2 = room.image2
        original_image3 = room.image3

        # Update room details in the database.
        room.room_name = room_name
        room.image1 = original_image1
        room.image2 = original_image2
        room.image3 = original_image3
        room.view = view
        room.width = width
        room.max_occupancy = int(max_occupancy)
        room.price = price
        room.description = description
        room.status = status

        db.session.commit()

        flash("Room details updated successfully", "success")
    else:
        flash("Room not found", "error")

    # Redirect back to the room details page.
    return redirect(url_for("admin.room_page"))

@room.route("/update_images/<int:room_id>", methods=['POST'])
def update_images(room_id):
    if request.method == "POST":
        # Get new image URLs from the form.
        new_image1 = request.form.get("image1")
        new_image2 = request.form.get("image2")
        new_image3 = request.form.get("image3")

        # Retrieve the room from the database.
        room = Room.query.get(room_id)
        if room:
            # Update the image URLs in the room object.
            room.image1 = new_image1
            room.image2 = new_image2
            room.image3 = new_image3

            # Commit the changes to the database.
            db.session.commit()

            flash("Room images updated successfully", "success")
        else:
            flash("Room not found", "error")

    # Redirect back to the room details page.
    return redirect(url_for("admin.room_page"))

# TO book a particular room
@room.route("/book-room/<int:room_id>", methods=["GET", "POST"])
@user_logged_in
def book_room(room_id):
    if request.method == "POST":
        # Get form data
        date_of_arrival_str = request.form.get("date_of_arrival")
        date_of_departure_str = request.form.get("date_of_departure")

        date_of_arrival = datetime.strptime(date_of_arrival_str, '%Y-%m-%d').date()
        date_of_departure = datetime.strptime(date_of_departure_str, '%Y-%m-%d').date()
        # Check if the arrival date is before the departure date
        if date_of_arrival >= date_of_departure:
            return render_template("user/room_details.html", error="Arrival date must be before departure date")

        # Check if the room is available based on its availability
        room = Room.query.get(room_id)
        if room.status != "available":
            return render_template("user/room_details.html", error="Room is not available for booking")

        # Create a new booking record in the database
        booking = Booking(date_of_arrival=date_of_arrival, date_of_departure=date_of_departure, status="pending", room_id=room_id, user_id=session["user_id"])
        db.session.add(booking)
        db.session.commit()

        # Redirect or render a success page
        return redirect(url_for("user.profile_page"))

    return render_template("user/room_details.html")


@room.route("/update-booking-status/<int:booking_id>", methods=["POST"])
def update_booking_status(booking_id):
    new_status = request.json.get("newStatus")

    # Retrieve the booking from the database based on the booking_id
    booking = Booking.query.get(booking_id)

    if booking:
        # Update the status of the booking
        booking.status = new_status

        # Save the changes to the database
        db.session.commit()

        return jsonify({"message": "Booking status updated successfully"})
    else:
        return jsonify({"message": "Booking not found"}, 404)

app/views/user.py
from flask import Blueprint, render_template, request, redirect, url_for, flash,  session 
import os
from flask import current_app
from ..config.database import db
from werkzeug.utils import secure_filename
from app.models import Room, User, Bookings
from app.config.variables import EMAIL_PASSWORD
from email_validator import validate_email, EmailNotValidError
import smtplib
from email.mime.text import MIMEText

def validate_guest_email( email_address):
    try:
        valid = validate_email(email_address)
        return True
    except EmailNotValidError as e:
        return False



user = Blueprint("user", __name__) 

# LOGIN ROUTE (VIEW)
@user.route("/")
@user.route("/home")
def landing_page():
    if 'registration_success' in session and session['registration_success']:
        flash("User registered successfully!", "success")
        session['registration_success'] = False
    elif 'login_success' in session and session['login_success']:
        flash("User login successful", "success")
        session['login_success'] = False
    return render_template("user/index.html")

@user.route("/register")
def register_page():
    return render_template("register.html")

@user.route("/login")
def login_page():
    return render_template("login.html")

@user.route("/nearbyplaces")
def nearbyplaces():
    page="Nearbyplaces"
    return render_template("user/nearbyplaces.html", page_name=page)


@user.route("/rooms")
def rooms_page():
    page="Rooms"
    rooms= Room.query.all()
    return render_template("user/rooms.html", page_name=page, rooms=rooms)

@user.route("/room-details/<int:room_id>")
def room_deets(room_id):
    room = Room.query.get(room_id)
    
    if not room:
        # Handle the case where the room with the given ID doesn't exist
        flash("Room not found", "error")
        return redirect(url_for("user.room_page"))
    
    return render_template("user/room_details.html", room=room, room_id=room_id)


@user.route("/contact_us", methods=['POST', 'GET'])
def contact_us():
    page="Contact"
    error = None  # Initialize the error variable
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        message = request.form.get('message')
        
        email_message = f'''Thank you {name} for reaching out to us! We have received your enquiry and wil get back to you shortly.
        
                
        - signed - MGT,
        Hotel Miariamar SG'''
        
        # Check for empty fields
        if not name or not email or not message:
            error = "All fields are required*"
            return render_template("user/contact_us.html", page_name=page,  error=error, name=name, email=email, message=message) 

        
        # Check for invalid email format
        if not error and not validate_guest_email(email):
            error = "Invalid email format*"
            return render_template("user/contact_us.html", page_name=page,  error=error, name=name, email=email, message=message)  

        
        if not error:
            fromx = 'testingweb3phoenix@gmail.com'
            to  = email
            msg = MIMEText(email_message)
            msg['Subject'] = "Enquiry - Miraiamar Hotel SG"
            msg['From'] = fromx
            msg['To'] = to

            try:
                # Creating connection using context manager
                with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp_server: 
                    smtp_server.login("testingweb3phoenix@gmail.com", EMAIL_PASSWORD)
                    smtp_server.sendmail(fromx, to, msg.as_string())
                    success_sent = 'Email sent successfully!, Google might some times sort this mails to spam, kindly check that too'
                    return render_template("user/contact_us.html", page_name=page, success_sent=success_sent)
            except Exception as e:
                error = f"An error occurred while sending the email: {str(e)}"

    return render_template("user/contact_us.html", page_name=page, error=error)

@user.route("/profile")
def profile_page():
    user_id = session.get('user_id')
    user = User.query.filter_by(id=user_id).first()
    bookings = Bookings.Booking.query.filter_by(user_id=user_id).all() if user_id else []
    return render_template("user/profile.html", user=user,bookings=bookings)


# Delete booking
@user.route("/cancel-booking/<int:booking_id>", methods=["GET", "POST"])
def cancel_booking(booking_id):
    booking = Bookings.Booking.query.get(booking_id)
    
    # Check if the booking exists and belongs to the logged-in user
    if booking and booking.user_id == session["user_id"]:
        # Delete the booking from the database
        db.session.delete(booking)
        db.session.commit()
        flash("Booking successfully cancelled", "success")
        return redirect(url_for("user.profile_page"))
    else:
        flash("Booking not found or you don't have permission to cancel it", "error")
        return redirect(url_for("user.profile_page"))
    
# So that the user can upload images to their profile
@user.route("/upload_image", methods=["POST"])
def upload_image():
    profile_img = request.files.get("img")

    if profile_img:
        # Ensure the folder exists before saving the image
        upload_path = os.path.join(current_app.root_path, 'static', 'user_uploads')
        if not os.path.exists(upload_path):
            os.makedirs(upload_path)

        # Get the current user
        user = User.query.get(session.get('user_id'))

        # Remove the old profile image if it exists
        if user.image:
            old_image_path = os.path.join(current_app.root_path, 'static', user.image)
            if os.path.exists(old_image_path):
                os.remove(old_image_path)

        # Generate a unique filename for the new image
        image_filename = secure_filename(profile_img.filename)
        image_path = os.path.join('user_uploads', image_filename)

        # Save the new image
        profile_img.save(os.path.join(upload_path, image_filename))

        # Update the user's image field in the database with the relative path to the saved image
        user.image = os.path.join('../../static/user_uploads', image_filename)
        flash("Image updated successfully", "success")
        db.session.commit()

    else:
        flash("Error", "error")
    return redirect(url_for('user.profile_page'))

# Function to check if the file extension is allowed
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in {'jpg', 'jpeg', 'png'}

# For the user to update their profile details    # 
@user.route("/update_profile", methods=["POST"])
def update_profile():
    username = request.form.get("username")
    email = request.form.get("email")

   # Additional checks can be added here
    if not username or not email:
        flash("Please provide both username and email", "error")
        return redirect(url_for("user.profile_page"))

    # Get the user from the database (assuming you have a User model)
    user = User.query.filter_by(id=session["user_id"]).first()

    if not user:
        flash("User not found", "error")
        return redirect(url_for("user.profile_page"))

    # Update user information
    user.username = username
    user.email = email
    # Commit changes to the database
    db.session.commit()

    flash("Profile updated successfully", "success")
    return redirect(url_for("user.profile_page"))

app/templates/user/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title%}Home{% endblock%}</title>

  <link rel="shortcut icon" href="{{ url_for('static', filename='user/SG_favicon.png') }}" type="image/x-icon">
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <!-- Font awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <!-- Font-Family -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Marcellus&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;0,1000;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900;1,1000&family=Roboto:wght@300&display=swap"
    rel="stylesheet">

  {% block customStyles %}{% endblock customStyles %}

  <!-- J-Query -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"
    integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <!-- Owl Carousel CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">

  <!-- Owl Carousel JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

  <!-- Include Flatpickr CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  <!-- Include Flatpickr JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

</head>

<body>
  <header>
    <ul>
      <li>Reservation number: <span id="color">(+91) 00000000</span></li>
      <li>401 Havelock Road, Singapore 169631</li>
      <a href="{{ url_for('user.rooms_page') }}">
        <li class="btn">BOOK YOUR STAY</li>
      </a>
    </ul>
  </header>
  <nav class="nav1">
    <ul class="gen-ul">
      <div class="brand-li">
        <a href="{{ url_for('static', filename='user/Hotel_Black.png') }}">
          <li><img src="../../static/user/Hotel_Black.png" alt="logo" class="logo"></li>
        </a>
      </div>
      <div class="other-li">
        <a href="{{ url_for('user.landing_page') }}">
          <li class="menu active">HOME</li>
        </a>
        <a href="{{ url_for('user.rooms_page') }}">
          <li class="menu">ROOMS</li>
        </a>
        <a href="{{ url_for('user.nearbyplaces') }}">
          <li class="menu">NEARBY PLACES</li>
        </a>
        <a href="{{ url_for('user.contact_us') }}">
          <li class="menu">CONTACT</li>
        </a>
        {% if "user_token" in session %}
        <a class="menu" href="{{ url_for('user.profile_page') }}"><i class="fa fa-user"></i></a>
        {% else %}
        <a href="{{ url_for('user.register_page')}}">
          <li class="menu">SIGN IN</li>
        </a>
        {% endif %}
      </div>
    </ul>
  </nav>

  <div class="other-li-side">
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('user.landing_page') }}"><img src="../../static/user/Hotel_Black.png"
            alt="logo" class="logo"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
          aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <iconify-icon icon="material-symbols-light:menu" class="menu"></iconify-icon>
        </button>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar"
          aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel"></h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
              aria-label="Close"></button>
          </div>
          <div class="offcanvas-body nav-body">
            <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link nav-li" aria-current="page" href="{{ url_for('user.landing_page') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.rooms_page') }}">Rooms</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.nearbyplaces') }}">Nearby Places</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.contact_us') }}">Contact</a>
              </li>
              <li>
                <a class="nav-link" href=""><i class="fa fa-user"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>


  {% block content %}

  {% endblock content %}

  <section class="footer-sect">
    <div class="footnote">
      <p class="foot-head">QUICK LINKS</p>
      <p>Home</p>
      <p>Nearby Places</p>
      <p>Rooms</p>
    </div>
    <div class="footnote">
      <p class="foot-head">ADDRESS</p>
      <p>401 Havelock Road,
        Singapore 169631</p>
    </div>
    <div class="footnote">
      <p class="foot-head">RESERVATONS</p>
      <p>(+91) 00000000</p>
      <p>support@hotel.com</p>
    </div>
    <div class="footnote">
      <p class="foot-head">FOLLOW US</p>
      <div class="social">
        <p><iconify-icon icon="mingcute:facebook-fill"></iconify-icon></p>
        <p><iconify-icon icon="mdi:twitter"></iconify-icon></p>
        <p><iconify-icon icon="mdi:youtube"></iconify-icon></p>
      </div>


    </div>
  </section>


  <!--User's css -->
  <link rel="stylesheet" href="{{ url_for('static', filename='user/style.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='user/index.css') }}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='user/nearby_places.css')}}">
  <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>

</body>

</html>

app/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
  
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
       
    <!-- Font-Family -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;0,1000;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900;1,1000&family=Roboto:wght@300&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="../../static/user/assets1/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="../../static/user/assets1/css/style.css">
</head>

<body>
    {% include "alerts.html" %}

    <div class="wrapper">
        <div class="left">
            <div class="bookings-head">
                <a href="{{ url_for('user.landing_page') }}"><i class="bi bi-arrow-left"></i></a>
                <h3 id="bookingsTabToggler">Bookings</h3>
                <h3 id="profileTabToggler">Profile</h3>
            </div>
            <div class="bookings" id="bookingsTab">
                <div class="shop__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Approved</th>
                                <th>Cancel</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if not bookings %}
                                <tr>
                                    <td colspan="5" class="text-center">No bookings yet</td>
                                </tr>
                            {% else %}
                                {% for booking in bookings %}
                                    <tr>
                                        <td class="cart__product__item">
                                            <img src="{{ booking.room.image1 }}" alt="{{ booking.room.room_name }}">
                                        </td>
                                        <td class="cart__price">{{ booking.room.room_name }}</td>
                                        <td class="cart__quantity">$ {{ booking.room.price }}</td>
                                        <td class="cart__total">
                                            {% if booking.status == "pending" %}
                                                <span class="text-secondary">Pending</span>
                                            {% elif booking.status == "Approved" %}
                                                <span class="text-success">Approved</span>
                                            {% else %}
                                                <span class="text-danger">Cancelled</span>
                                            {% endif %}
                                        </td>
                                        <td class="cart__close">
                                            <a href="{{ url_for('user.cancel_booking', booking_id=booking.id) }}"><span class="bi bi-x"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="profile" id="profileTab">
            <div class="content">
                <div class="top-content">
                    <form id="image-upload-form" action="{{ url_for('user.upload_image') }}" method="POST" enctype="multipart/form-data">
                        <input type="file" id="image-upload-input" name="img" accept="image/*" style="display: none">
                        <img src="{{ user.image }}" id="upload-button" alt="Upload Image" onclick="document.getElementById('image-upload-input').click()"
                        style="height: auto; width: 12vw;">
                    </form>                               
                    
                    <!-- Viewing mode -->
                    <div id="view-mode">
                        <p>{{ user.username }} <a href="#" id="edit-button"><i class="bi bi-pencil"></i></a></p>
                        <p>{{ user.email }}</p>
                    </div>
                
                    <!-- Editing mode (hidden by default) -->
                    <div id="edit-mode" class="profile_form" style="display: none;">
                        <form action="{{ url_for('user.update_profile') }}" method="POST">
                            <input class="mb-2" name="username" type="text" id="username-input" value="{{ user.username }}"> <br>
                            <input  type="email" name="email" id="email-input" value="{{ user.email }}"> <br>
                            <button type="submit" id="submit">Save</button>
                            <button id="cancel-button">Cancel</button>
                        </form>
                    </div>
                </div>
                
                
                <div class="bottom-content">
                    <p>Hope you have a wonderful stay</p>
                    <a class="btn-logout" href="{{ url_for('auth.logout')}}"><li  class="menu">LOGOUT</li></i></a>
                </div>
            </div>
        </div>
    </div>

    <script src="../../static/user/assets1/js/main.js"></script>
</body>

</html>

app/templates/user/rooms.html
{% extends "page_header.html" %}

{% block title %}
Rooms - Miriamar
{% endblock title %}

{% block parent_content %}
<div class="container-fluid ">
    <div class="row overlay justify-content-evenly mt-3 mb-3">
      {% for room in rooms %}
        <div class="col-lg-4 col-md-6 col-sm-12 room-card">
          <a href="{{ url_for('user.room_deets', room_id=room.id) }}">
            <div class="room-image">
              <img src="{{ room.image1 }}" alt="Room Image">
              <div class="bottom-left">
                <div class="stars">
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                </div>
              </div>

              <div class="bottom-right">
                <div class="price">$ {{ room.price }}</div>
                <div class="" style="color: black;"><h1>{{ room.room_name }}</h1></div>
              </div>
            </div>
          </a>

          <div class="room-details">
            <p class="room-width">{{ room.width }} . {{ room.view }}</p>
          </div>
        </div>
        {% endfor %} 

    </div>
</div>

{% endblock parent_content%}