app/views/auth.py
from datetime import timedelta, datetime
import  secrets, string
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
from app.models.Token import PasswordResetToken
from ..config.database import db
from ..models import User, Room, Booking
from .decorators import user_exists_required
from werkzeug.security import generate_password_hash, check_password_hash
from flask_jwt_extended import create_access_token, jwt_required, get_jwt_identity

auth = Blueprint("auth", __name__)

@auth.route("/register", methods=["POST"])
def register():
    # Get user input from the request
    email = request.form.get("email").strip()
    username = request.form.get("username").strip()
    password = request.form.get("password").strip()
    session["original_url"] = request.referrer  # the current route

    # Check if any required field is empty
    if not email or not username or not password:
        flash("Please provide all required information", "error")
        return redirect(url_for("user.register_page"))
    
    valid, message = check_detail_authenticity(email, password)
    if not valid:
        flash(message, "error")
        return redirect(url_for("user.register_page"))
    
    # Check if the user already exists
    user = User.query.filter_by(email=email).first()
    if user:
        flash("Email already exists", "error")
        return redirect(url_for("user.login_page"))
 
    # For regular user registration
    user = User(
        username=username,
        email=email,
        password=password,
        role="user"
    )
    db.session.add(user)
    db.session.commit()
    
    session['user_id'] = user.id #store user id
    session['registration_success'] = True
    # Generate a token for the user and store it in a session
    expiry_time = timedelta(days=30)  # Set your desired token expiration time
    token = create_access_token(identity=user.id, expires_delta=expiry_time)
    session["user_token"] = token  # Store the token in the session
    print("Token stored in session")

    # After registration
    return redirect(url_for("user.landing_page"))

    
# Checks the viability of the input details
def check_detail_authenticity(email, password):
    if '@' not in email:
        return False, "Incorrect email"

    if len(password) < 8:
        return False, "Password length should be at least 8 characters"

    return True, "Valid details"

# The login route handling logic
@auth.route("/login", methods=["POST"])
@user_exists_required
def login():
    email = request.form.get("email").strip()
    password = request.form.get("password").strip()
    print(session.get('role'))

    # Check for empty inputs
    if not email or not password:
        flash("Please provide both email and password", "error")
        return redirect(url_for("user.login_page"))

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash("Invalid email or password", "error")
        return redirect(url_for("user.login_page"))
    
    # Handle token generation if needed
    expiry_time = timedelta(days=30)
    token = create_access_token(identity=user.id, expires_delta=expiry_time)

    # Store user deets in session
    session["role"] = user.role
    session["user_id"] = user.id
    session["user_token"] = token
    session['login_success'] = True

    if user.role == "admin":
        # Handle admin access
        flash("Admin login successful", "success")
        return redirect(url_for("admin.home_page"))
    else:
        return redirect(url_for("user.landing_page"))

# To render template to reset password
@auth.route("/password-reset-request")
def request_password_reset():
    # Retrieve the user's email from the request
    user_id = session.get('user_id')
    
    # Generate a unique token
    token = token = ''.join(secrets.choice(string.ascii_letters + string.digits) for _ in range(32))

    # Set the token's expiration (e.g., one hour from now)
    expiration = datetime.utcnow() + timedelta(hours=1)

    # Store the token and user email in the database
    password_reset_token = PasswordResetToken(user_id, token=token, expiration=expiration)
    if not user_id:
        flash("Login to access this page", "error")
        return redirect(url_for('user.login_page'))
    db.session.add(password_reset_token)
    db.session.commit()

    print(password_reset_token)
    # Allow the user to reset their password locally
    return render_template("password_reset.html", token=token)

# To authenticate the password reset
@auth.post("/password-reset/<token>")
def reset_password(token):
    user_id = session.get('user_id')
    # Look up the token in the database
    password_reset_token = PasswordResetToken.query.filter_by(token=token).first()
    print(f"User id: {user_id}")
    if password_reset_token and datetime.utcnow() <= password_reset_token.expiration:
        # Token is valid
        # Get the user associated with the token
        user = User.query.filter_by(id=user_id).first()

        if user:
            # Update the user's password (you'll need to implement a function to update the password)
            new_password = request.form.get("password")
            user.password = generate_password_hash(new_password)

            # Remove the token from the database
            db.session.delete(password_reset_token)
            db.session.commit()

            # Flash a success message
            flash("Password reset successfully. You can now log in with your new password.", "success")

            # Redirect the user to the login page
            return redirect(url_for("user.login_page"))
        else:
            flash("Invalid user.", "error")
    else:
        # Invalid or expired token; inform the user
        flash("Invalid or expired token.", "error")
        return redirect(url_for("auth.request_password_reset"))


# To logout user
@auth.route("/logout")
def logout():
    user_id = session.get("user_id")  # Store the user_id before clearing the session
    session.clear()  # Clear the entire session
    session["user_id"] = user_id  # Restore the user_id to the session

    # Redirect the user to the landing page or any other desired page
    return redirect(url_for("user.landing_page"))

app/templates/alerts.html
{% set alerts = get_flashed_messages(with_categories=True) %}
<style>
  .alert-container {
    position: fixed;
    width: 100%;  
    top: 50px;
    right: 50px;
    z-index: 9999;
    max-width: 300px;
  }
  .alert-container > .alert { 
    width: 100% !important;
  }
</style>
{% if alerts|length %}
  <div class="alert-container">
    {% for category, message in alerts %}
    <div class="alert alert-dismissible text-bg-primary border-0 fade show alert-{{ 'danger' if category == 'error' else category }}" role="alert">
      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
       {{ message }}
    </div>
    {% endfor %}
  </div>
{% endif %}

app/templates/auth_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock%}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='user/style.css') }}">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <!-- Font-Family -->
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&display=swap" rel="stylesheet">

</head>
<body class="auth_bg">
    {% block content %}
   
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</body>
</html>

app/templates/error_404.html
{% if "user_token" in session %}
    {% if session["user_role"] == "admin" %}
        {% extends "admin/base.html" %}
    {% else %}
        {% extends "user/base.html" %}
    {% endif %}
{% else %}
    {% extends "user/base.html" %}
{% endif %}

{% block title %}
Page not found - Miriamar
{% endblock title %}

{% block customStyles %}
<link rel="stylesheet" href="{{ url_for('static', filename='errors.css') }}">
{% endblock customStyles %}

{% block content %}


    <section class="error_404_container">
        <div class="error_bg_img"></div>
        <h1 class="text_404">404</h1>
        <span class="error_text">Oops! Page Not Found</span>
        <p class="error_text_desc">Page doesn’t exist or some other error occurred. Go to our Home page or go back to Previous page</p>

        <a href="{{ url_for('user.landing_page') }}"><button class="back_to_homepage_btn" type="button">Back To Homepage</button></a>
    </section>

{% endblock content %}

app/templates/error_500.html
{% if "user_token" in session %}
    {% if session["user_role"] == "admin" %}
        {% extends "admin/base.html" %}
    {% else %}
        {% extends "user/base.html" %}
    {% endif %}
{% else %}
    {% extends "user/base.html" %}
{% endif %}

{% block title %}
Internal server error - Miriamar
{% endblock title %}

{% block customStyles %}
<link rel="stylesheet" href="{{ url_for('static', filename='errors.css') }}">
{% endblock customStyles %}

{% block content %}
<section class="error_404_container">
    <div class="error_bg_img"></div>
    <h1 class="text_404">500</h1>
    <span class="error_text">Oops! Internal Server Error</span>
    <p class="error_text_desc">Something went wrong from our side. Try refreshing the browser or go back to Previous page</p>

    <a href="{{ url_for('user.landing_page') }}"><button class="back_to_homepage_btn" type="button">Back To Homepage</button></a>
</section>
{% endblock content %}

app/templates/login.html
{% extends "auth_base.html" %}

{% block title %}
Login -Miramar
{% endblock title %}

<!-- For alerts -->
{% include "alerts.html" %}

{% block content %}
<div class="container justify-content-center d-flex my-5 pt-5">
    <div class="row neumorphic-card">
        <div class="col-md-6 auth_img image-overlay">
        </div>
        
        <div class="col-md-6">
                <div class=" auth-card p-4">
                    <div class="text-center">
                        <img src="{{ url_for('static', filename='user/Hotel_Black.png') }}" alt="Company Logo" class="logo img-fluid" width="100">
                    </div>
                
                    <h2 class="mb-4 mt-3 auth_font text-center">Login</h2>
                    <form class="lgr" action="{{ url_for('auth.login') }}"  method="post">
                        <div class="mb-3">
                            <label for="email" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
                            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>

                        </div>
                
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Password</label>
                            <input type="password" class="form-control" name="password" id="exampleInputPassword1">
                        </div>
                
                        <a href="{{ url_for('auth.request_password_reset') }}" style="color: #808080;">Forgot password?</a>
                        <div class="text-center button mt-3">
                            <input type="submit" class="form-control" id="submit" name="submit">
                        </div>
                        
                    </form>
                </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/page_header.html
{% extends "user/base.html" %}
{% block content %}
<div class="col-md-6 pg_image-overlay image-overlay d-flex flex-column justify-content-center align-items-center mb-5">
    <div class="mb-4 mt-3 auth_font text-center">
        <h1 class="fs-md-18 fs-lg-24 overflow-hidden"
            style="color: white;position: relative;z-index: 1; font-size: 8vw">{{ page_name }}</h1>
    </div>
    <nav style="--bs-breadcrumb-divider: '>'; color: white;" aria-label="breadcrumb">
        <ol class="breadcrumb" style="color: white;position: relative;z-index: 1;">
            <li class="breadcrumb-item"><a href="{{ url_for('user.landing_page') }}"
                    style="color: white; text-decoration: none;">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page" style="color: white;">{{ page_name }}</li>
        </ol>
    </nav>
</div>

{% block parent_content %}{% endblock parent_content %}
<!-- I made use of it in  rooms.html in user folder, you can check it out.-->
{% endblock content %}

app/templates/password_reset.html
{% extends "auth_base.html" %}

{% block title %}
Login -Miraiamar
{% endblock title %}

<!-- For alerts -->
{% include "alerts.html" %}

{% block content %}
<div class="container justify-content-center d-flex my-5 pt-5" style="width: 50%;">
    <div class="row ">
        <div class="col-md-12 pb-5">
                <div class=" auth-card p-4">
                    <div class="text-center">
                        <img src="{{ url_for('static', filename='user/Hotel_Black.png') }}" alt="Company Logo" class="logo img-fluid" width="100">
                    </div>
                
                    <h2 class="mb-4 mt-3 auth_font text-center">Password Reset</h2>
                    <form class="lgr" action="{{ url_for('auth.reset_password', token=token) }}" method="post">
                        <div class="mb-3">
                            <label for="password" class="form-label">New Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <!-- Add password confirmation fields if needed -->
                        <div class="text-center button mt-3">
                            <input type="submit" class="form-control" id="submit" name="submit" value="Reset Password">
                        </div>
                    </form>
                </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/register.html
{% extends "auth_base.html" %}

{% block title %}
Register -Miramar
{% endblock title %}

<!-- For the alerts -->
{% include "alerts.html" %}

{% block content %}
<div class="container  justify-content-center d-flex my-5 pt-5">
    <div class="row neumorphic-card">
        <div class="col-md-6 auth_img image-overlay">
        </div>

        <div class="col-md-6">
            <div class=" auth-card p-4">
                <div class="text-center">
                    <img src="{{ url_for('static', filename='user/Hotel_Black.png') }}" alt="Company Logo"
                        class="logo img-fluid" width="100">
                </div>

                <h2 class="mb-4 mt-3 auth_font text-center">Sign Up</h2>
                <form class="lgr" action="{{ url_for('auth.register') }}" method="post">
                    <div class="mb-3">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>

                    <div class="mb-3">
                        <label for="email" class="form-label">Date of Birth</label>
                        <input type="date" class="form-control" max="2050-01-01" id="DOB" name="DOB"
                            aria-describedby="DOB">
                    </div>

                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
                        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>

                    </div>

                    <div class="mb-3">
                        <label for="Password" class="form-label">Password</label>
                        <input type="password" class="form-control" name="password" id="Password">
                    </div>

                    <a href="{{ url_for('auth.login') }}" style="color: #808080;">Already signed in? Login</a>
                    <div class="text-center button mt-3">
                        <input type="submit" class="form-control" id="submit" name="submit">
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}